version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"
    volumes:
      - C:\work_space\docker\rox\db:/var/lib/postgresql/data
